### ISSUE TITLE
Add an option to disable ANSI color codes in logging output

### ISSUE THREAD

**Issue by SuperTux88** [denschub/camo-rs#11]
At the moment the logging always logs with ANSI color codes to format the logs. That's fancy if you have a terminal that can show colors, but it makes the logs extremely hard to read if you run it as a service and just log the output.

So it would be useful to have an option to only log plain text without ANSI codes. Bonus points for an option to log as JSON instead.

**Comment by SuperTux88** [comment]
For me, yes, as I collect my logs and can automatically parse the JSON to make the fields readable again. But for other people who just have a logfile and want a human-readable output (but maybe without color codes), a plain (no colors, no JSON) would maybe still be useful?

**Comment by denschub** [comment]
> who just have a logfile and want a human-readable output (but maybe without color codes), a plain (no colors, no JSON) would maybe still be useful?

Yeah, fair. :)

**Comment by denschub** [comment]
I implemented `--log-level` and `--log-format` flags (and corresponding env vars) in `develop`. Will build a `0.3.0` release in a moment, I think this is useful enough to ship a new preview release.
